package browser

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
)

type geckoAdapter struct {
	id         string
	candidates []string
	launcher   Launcher
}

// NewGeckoAdapter creates an adapter for one Gecko-family identifier.
func NewGeckoAdapter(id string, candidates []string, launcher Launcher) Adapter {
	if launcher == nil {
		launcher = execLauncher{}
	}
	return &geckoAdapter{id: id, candidates: append([]string(nil), candidates...), launcher: launcher}
}

func (a *geckoAdapter) ID() string { return a.id }

func (a *geckoAdapter) Detect(ctx context.Context) ([]Installation, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	var installations []Installation
	for _, candidate := range a.candidates {
		info, err := os.Stat(candidate)
		if err == nil && !info.IsDir() && info.Mode()&0o111 != 0 {
			installations = append(installations, Installation{ID: a.id, Executable: candidate})
		}
		if err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("inspect %s executable: %w", a.id, err)
		}
	}
	return installations, nil
}

func (a *geckoAdapter) PrepareProfile(ctx context.Context, session Session, installation Installation) (Profile, error) {
	if err := ctx.Err(); err != nil {
		return Profile{}, err
	}
	path := filepath.Join(session.ProfileRoot, session.Key, a.id)
	if err := os.MkdirAll(path, 0o700); err != nil {
		return Profile{}, fmt.Errorf("create %s profile: %w", a.id, err)
	}
	if err := os.Chmod(path, 0o700); err != nil {
		return Profile{}, fmt.Errorf("protect %s profile: %w", a.id, err)
	}
	preferences := fmt.Sprintf(`// Generated by Kamui. Manual edits are overwritten.
user_pref("network.proxy.type", 1);
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", %d);
user_pref("network.proxy.ssl", "127.0.0.1");
user_pref("network.proxy.ssl_port", %d);
user_pref("network.proxy.no_proxies_on", "");
user_pref("network.proxy.allow_hijacking_localhost", true);
`, session.Proxy.Port(), session.Proxy.Port())
	temporary, err := os.CreateTemp(path, "user.js-*")
	if err != nil {
		return Profile{}, fmt.Errorf("create temporary user.js: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o600); err != nil {
		temporary.Close()
		return Profile{}, fmt.Errorf("protect temporary user.js: %w", err)
	}
	if _, err := temporary.WriteString(preferences); err != nil {
		temporary.Close()
		return Profile{}, fmt.Errorf("write user.js: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return Profile{}, fmt.Errorf("close user.js: %w", err)
	}
	if err := os.Rename(temporaryPath, filepath.Join(path, "user.js")); err != nil {
		return Profile{}, fmt.Errorf("install user.js: %w", err)
	}
	return Profile{Path: path, Session: session, Installation: installation}, nil
}

func (a *geckoAdapter) Launch(ctx context.Context, profile Profile, urls []string) error {
	args := []string{"-no-remote", "-profile", profile.Path}
	args = append(args, urls...)
	if err := a.launcher.Launch(ctx, profile.Installation.Executable, args); err != nil {
		return fmt.Errorf("launch %s: %w", a.id, err)
	}
	return nil
}

func (a *geckoAdapter) Open(ctx context.Context, profile Profile, urls []string) error {
	args := []string{"-profile", profile.Path}
	for _, target := range urls {
		args = append(args, "-new-tab", target)
	}
	if err := a.launcher.Launch(ctx, profile.Installation.Executable, args); err != nil {
		return fmt.Errorf("open in %s: %w", a.id, err)
	}
	return nil
}

// DefaultGeckoAdapters returns Gecko-family adapters in deterministic order.
func DefaultGeckoAdapters(launcher Launcher) []Adapter {
	return []Adapter{
		NewGeckoAdapter("firefox", browserPaths("Firefox.app/Contents/MacOS/firefox"), launcher),
		NewGeckoAdapter("firefox-developer-edition", browserPaths("Firefox Developer Edition.app/Contents/MacOS/firefox"), launcher),
		NewGeckoAdapter("zen", browserPaths("Zen.app/Contents/MacOS/zen"), launcher),
		NewGeckoAdapter("librewolf", browserPaths("LibreWolf.app/Contents/MacOS/librewolf"), launcher),
		NewGeckoAdapter("floorp", browserPaths("Floorp.app/Contents/MacOS/floorp"), launcher),
	}
}

// DefaultAdapters returns every initially supported browser adapter.
func DefaultAdapters(launcher Launcher) []Adapter {
	adapters := DefaultChromiumAdapters(launcher)
	return append(adapters, DefaultGeckoAdapters(launcher)...)
}
