package browser

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
)

type geckoAdapter struct {
	adapterBase
}

// NewGeckoAdapter creates an adapter for one Gecko-family identifier.
func NewGeckoAdapter(id string, candidates []string, launcher Launcher) Adapter {
	return &geckoAdapter{adapterBase: newAdapterBase(id, candidates, launcher)}
}

func (a *geckoAdapter) PrepareProfile(ctx context.Context, session Session, installation Installation) (Profile, error) {
	path, err := a.prepareProfileDirectory(ctx, session)
	if err != nil {
		return Profile{}, err
	}
	preferences := fmt.Sprintf(`// Generated by Kamui. Manual edits are overwritten.
user_pref("network.proxy.type", 1);
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", %d);
user_pref("network.proxy.ssl", "127.0.0.1");
user_pref("network.proxy.ssl_port", %d);
user_pref("network.proxy.no_proxies_on", "");
user_pref("network.proxy.allow_hijacking_localhost", true);
`, session.Proxy.Port(), session.Proxy.Port())
	temporary, err := os.CreateTemp(path, "user.js-*")
	if err != nil {
		return Profile{}, fmt.Errorf("create temporary user.js: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o600); err != nil {
		temporary.Close()
		return Profile{}, fmt.Errorf("protect temporary user.js: %w", err)
	}
	if _, err := temporary.WriteString(preferences); err != nil {
		temporary.Close()
		return Profile{}, fmt.Errorf("write user.js: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return Profile{}, fmt.Errorf("close user.js: %w", err)
	}
	if err := os.Rename(temporaryPath, filepath.Join(path, "user.js")); err != nil {
		return Profile{}, fmt.Errorf("install user.js: %w", err)
	}
	return Profile{Path: path, Session: session, Installation: installation}, nil
}

func (a *geckoAdapter) Launch(ctx context.Context, profile Profile, urls []string) error {
	if _, err := os.Lstat(filepath.Join(profile.Path, ".parentlock")); err == nil {
		return a.Open(ctx, profile, urls)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("inspect %s profile lock: %w", a.id, err)
	}
	args := []string{"-no-remote", "-profile", profile.Path}
	args = append(args, urls...)
	if err := a.launcher.Launch(ctx, profile.Installation.Executable, args); err != nil {
		return fmt.Errorf("launch %s: %w", a.id, err)
	}
	return nil
}

func (a *geckoAdapter) Open(ctx context.Context, profile Profile, urls []string) error {
	args := []string{"-profile", profile.Path}
	for _, target := range urls {
		args = append(args, "-new-tab", target)
	}
	if err := a.launcher.Launch(ctx, profile.Installation.Executable, args); err != nil {
		return fmt.Errorf("open in %s: %w", a.id, err)
	}
	return nil
}

func (a *geckoAdapter) Close(ctx context.Context, profile Profile) error {
	stopper, ok := a.launcher.(ProfileStopper)
	if !ok {
		return nil
	}
	return stopper.Stop(ctx, profile.Installation.Executable, []string{"-profile", profile.Path})
}
