package browser_test

import (
	"context"
	"net/netip"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/narasaka/kamui/internal/browser"
)

func TestGeckoWritesManagedProxyPreferencesAndLaunchesSeparateProfile(t *testing.T) {
	t.Parallel()

	launcher := &recordingLauncher{}
	adapter := browser.NewGeckoAdapter("firefox", []string{"/Applications/Firefox.app/Contents/MacOS/firefox"}, launcher)
	session := browser.Session{
		Key:         "host-key",
		Proxy:       netip.MustParseAddrPort("127.0.0.1:52144"),
		ProfileRoot: t.TempDir(),
	}
	installation := browser.Installation{ID: "firefox", Executable: "/Applications/Firefox.app/Contents/MacOS/firefox"}
	profile, err := adapter.PrepareProfile(context.Background(), session, installation)
	if err != nil {
		t.Fatalf("PrepareProfile returned error: %v", err)
	}
	preferences, err := os.ReadFile(filepath.Join(profile.Path, "user.js"))
	if err != nil {
		t.Fatal(err)
	}
	wantPreferences := `// Generated by Kamui. Manual edits are overwritten.
user_pref("network.proxy.type", 1);
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", 52144);
user_pref("network.proxy.ssl", "127.0.0.1");
user_pref("network.proxy.ssl_port", 52144);
user_pref("network.proxy.no_proxies_on", "");
user_pref("network.proxy.allow_hijacking_localhost", true);
`
	if got := string(preferences); got != wantPreferences {
		t.Fatalf("user.js =\n%s\nwant:\n%s", got, wantPreferences)
	}
	if err := adapter.Launch(context.Background(), profile, []string{"http://localhost:3000"}); err != nil {
		t.Fatal(err)
	}
	wantArgs := []string{"-no-remote", "-profile", profile.Path, "http://localhost:3000"}
	if launcher.path != installation.Executable || !reflect.DeepEqual(launcher.args, wantArgs) {
		t.Fatalf("launch = %q %#v, want %q %#v", launcher.path, launcher.args, installation.Executable, wantArgs)
	}
}
